name: Agent Protection

on:
  pull_request:
    branches: [ main ]

jobs:
  agent-protection-check:
    name: Agent Protection Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Check for protected file modifications
        continue-on-error: true
        run: |
          VIOLATION=0
          if [ ! -f .noagent ]; then
            echo "::warning::.noagent configuration file not found. Cannot enforce agent protection rules."
            exit 0
          fi
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)
          PROTECTED_FILES=$(grep -v '^#' .noagent | grep -v '^$')
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_COMMITS=$(git log --format=%B origin/${{ github.base_ref }}..HEAD)
          if [[ "$PR_TITLE" == *"[HUMAN EDIT]"* ]] || [[ "$PR_BODY" == *"[HUMAN EDIT]"* ]]; then
            echo "Human edit override tag detected in PR. Skipping protected file checks."
            exit 0
          fi
          AI_PATTERN="automated by|copilot change|agent modification|\[bot\]|auto-generated|ai-assisted|generated by|created by ai|suggested by|co-authored by"
          if echo "$PR_COMMITS" | grep -iE "$AI_PATTERN" > /dev/null; then
            echo "Detected potentially automated commits. Checking for protected file modifications..."
            for file in $CHANGED_FILES; do
              for pattern in $PROTECTED_FILES; do
                if [[ "$file" == $pattern ]] || [[ "$file" == $(eval echo $pattern) ]]; then
                  echo "::warning::Protected file '$file' was modified in what appears to be an automated commit."
                  echo "Evidence: Commit message contains AI/bot-related terms"
                  VIOLATION=1
                  break
                fi
              done
            done
          fi
          if [[ "$VIOLATION" -eq 1 ]]; then
            echo "::warning::Protected files were modified by what appears to be an automated process."
            echo "::warning::If this is a legitimate human edit, please add [HUMAN EDIT] to your PR title or description."
          else
            echo "No evidence of automated modifications to protected files detected. Approved."
          fi
