name: Agent Protection Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"

jobs:
  check-protected-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for protected file modifications
        run: |
          # Initialize violation flag
          VIOLATION=0
          
          # Check if .noagent file exists
          if [ ! -f .noagent ]; then
            echo "::warning::.noagent configuration file not found. Cannot enforce agent protection rules."
            exit 0
          fi
          
          # Get changed files in PR
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)
          
          # Extract protected files/patterns (skip comments and empty lines)
          PROTECTED_FILES=$(grep -v '^#' .noagent | grep -v '^$')
          
          # Get PR information
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_COMMITS=$(git log --format=%B origin/${{ github.base_ref }}..HEAD)
          
          # Look for manual override tag in PR title or body
          if [[ "$PR_TITLE" == *"[HUMAN EDIT]"* ]] || [[ "$PR_BODY" == *"[HUMAN EDIT]"* ]]; then
            echo "Human edit override tag detected in PR. Skipping protected file checks."
            exit 0
          fi
          
          # Check for evidence of AI or bot-generated commits
          AI_PATTERN="automated by|copilot change|agent modification|\[bot\]|auto-generated|ai-assisted|generated by|created by ai|suggested by|co-authored by"
          
          # Check commit messages for AI patterns
          if echo "$PR_COMMITS" | grep -iE "$AI_PATTERN" > /dev/null; then
            echo "Detected potentially automated commits. Checking for protected file modifications..."
            
            # Look for modified protected files
            for file in $CHANGED_FILES; do
              for pattern in $PROTECTED_FILES; do
                # Check if file matches pattern (handle glob patterns)
                if [[ "$file" == $pattern ]] || [[ "$file" == $(eval echo $pattern) ]]; then
                  echo "::error::Protected file '$file' was modified in what appears to be an automated commit."
                  echo "Evidence: Commit message contains AI/bot-related terms"
                  VIOLATION=1
                  break
                fi
              done
            done
          fi
          
          # Fail the workflow if violations found
          if [[ "$VIOLATION" -eq 1 ]]; then
            echo "Protected files were modified by what appears to be an automated process."
            echo "If this is a legitimate human edit, please add [HUMAN EDIT] to your PR title or description."
            exit 1
          else
            echo "No evidence of automated modifications to protected files detected. Approved."
          fi
