name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Go binaries
        run: make build-all
      
      - name: Create checksums
        run: |
          mkdir -p dist
          cp bin/* dist/
          cd dist && find . -type f -name "mathreleaser*" | xargs shasum -a 256 > checksums.txt

      - name: Check if release notes exist
        id: check_files
        run: |
          if [ -f "release-notes/${{ steps.tag.outputs.tag }}/GITHUB_RELEASE.md" ]; then
            echo "release_notes_exist=true" >> $GITHUB_OUTPUT
          else
            echo "release_notes_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: "Release ${{ steps.tag.outputs.tag }}"
          bodyFile: ${{ steps.check_files.outputs.release_notes_exist == 'true' && format('release-notes/{0}/GITHUB_RELEASE.md', steps.tag.outputs.tag) || '' }}
          artifacts: "dist/*"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Archive Changelog Entries
        run: |
          echo "Archiving changelog entries for ${{ steps.tag.outputs.tag }}"
          ./scripts/archive-changelog.sh "${{ steps.tag.outputs.tag }}"
          
      - name: Commit Archive Changes
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .changelog/archive
          git add -u .changelog
          git commit -m "Archive changelog entries for ${{ steps.tag.outputs.tag }}" || echo "No changes to commit"
          git push origin HEAD:main