
name: Integration Tests

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    # Removed invalid needs dependency
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      - name: Get dependencies
        run: go mod download
      - name: Build binary for testing
        run: go build -o bin/mathreleaser-test ./cmd/mathreleaser
      - name: Run integration tests
        run: ./scripts/run-integration-tests.sh
