name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Run at midnight every Sunday
  workflow_dispatch:

jobs:
  # Basic CI testing job
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

  # Linting job (Go and Shell)
  lint:
    name: Lint
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4


      # Go linting is not run in CI. Please run 'make devcheck' locally before pushing changes.
      - name: Linting instructions
        run: |
          echo "Go linting is not enforced in CI. Please run 'make devcheck' locally before pushing."

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          SCRIPTS=$(find . -name "*.sh" -type f | sort)
          SCRIPTS+=" $(find . -type f ! -path "*/\.*" ! -path "*/vendor/*" ! -path "*/node_modules/*" -perm +111 -exec grep -l '^\#\!/bin/bash\|^\#\!/usr/bin/env bash\|^\#\!/bin/sh' {} \; 2>/dev/null | sort -u || true)"
          for script in $SCRIPTS; do
            echo "Checking $script"
            shellcheck -x "$script" || exit 1
          done

      - name: Install shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run shfmt
        run: |
          SCRIPTS=$(find . -name "*.sh" -type f | sort)
          SCRIPTS+=" $(find . -type f ! -path "*/\.*" ! -path "*/vendor/*" ! -path "*/node_modules/*" -perm +111 -exec grep -l '^\#\!/bin/bash\|^\#\!/usr/bin/env bash\|^\#\!/bin/sh' {} \; 2>/dev/null | sort -u || true)"
          for script in $SCRIPTS; do
            echo "Checking $script"
            shfmt -i 2 -ci -bn -s -d "$script" || exit 1
          done

  # Security scanning job - combines GoSec, govulncheck, and partial CodeQL setup
  security-scan:
    name: Security Scan
    needs: [test, lint]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Get dependencies
        run: go mod download

      # GoSec security scanning
      - name: Run GoSec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          # First run with text output to see issues in logs
          gosec -no-fail ./...
          # Then run with SARIF output for GitHub security dashboard integration
          # Continue-on-error flag ensures workflow doesn't fail if security issues are found
          gosec -fmt=sarif -out=gosec.sarif ./... || echo "::warning::Security issues found, but continuing pipeline"
        
      - name: Upload GoSec scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif

      # Vulnerability checking
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./... || echo "::warning::Vulnerabilities found, but continuing pipeline"

  # CodeQL analysis job
  codeql-analysis:
    name: CodeQL Analysis
    needs: test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # Build job that runs after all tests and security checks have passed
  build:
    name: Build
    # Require all security jobs to pass before building
    needs: [test, lint, security-scan, codeql-analysis]
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: gorelease
        path: bin/gorelease