name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      
      - name: Get dependencies
        run: go mod download
      
      - name: Build all platforms
        run: make build-all
      
      - name: Generate checksums
        run: |
          mkdir -p dist
          cp bin/* dist/
          cd dist && find . -type f -name "gorelease*" | xargs sha256sum > checksums.txt
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Creating release for tag $TAG"
          
          # Create a release
          gh release create "$TAG" \
            --title "Release $TAG" \
            --notes-file GITHUB_RELEASE_NOTES.md \
            --draft=false \
            dist/*
