name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      
      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      
      - name: Get dependencies
        run: go mod download
      
      - name: Generate Release Notes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Generating release notes for $TAG"
          # First generate the release notes from changelog entries
          ./scripts/generate-release-notes.sh "$TAG"
          # Then format them into GitHub and human-friendly formats
          ./scripts/format-release-notes.sh "$TAG"
          # Copy the GitHub release notes to the root for the GitHub release
          cp "release-notes/$TAG/GITHUB_RELEASE.md" GITHUB_RELEASE_NOTES.md
      
      - name: Build all platforms
        run: make build-all
      
      - name: Generate checksums
        run: |
          mkdir -p dist
          cp bin/* dist/
          cd dist && find . -type f -name "mathreleaser*" | xargs sha256sum > checksums.txt
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Creating release for tag $TAG"
          
          # Create a release
          gh release create "$TAG" \
            --title "Release $TAG" \
            --notes-file GITHUB_RELEASE_NOTES.md \
            --draft=false \
            dist/*
            
      - name: Archive Changelog Files
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Since we're in detached HEAD state, we'll skip the commit step
          ./scripts/archive-changelog.sh "$TAG"
