name: Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    # Removed invalid needs dependency
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      - name: Get dependencies
        run: go mod download
      - name: Run GoSec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -no-fail ./...
          gosec -fmt=sarif -out=gosec.sarif ./... || echo "::warning::Security issues found, but continuing pipeline"
      - name: Upload GoSec scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          GOVERSION=go1.24.5 govulncheck ./... || echo "::warning::Vulnerabilities found, but continuing pipeline"
